[phases.setup]
nixPkgs = ["nodejs-22_x", "python3", "gnumake", "gcc"]

[phases.install]
cmds = ["npm ci", "npm rebuild sqlite3 --build-from-source"]

[phases.build]
cmds = []

[start]
cmd = "node server.js"

